import os

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet

from app.services.soil_interpretation import (
    interpret_soil_test
)


def generate_soil_health_report(
    farmer,
    soil_test
):
    # Create reports directory
    os.makedirs("reports", exist_ok=True)

    file_path = f"reports/{soil_test.sample_code}.pdf"

    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4
    )

    styles = getSampleStyleSheet()

    elements = []

    # =========================================
    # Title
    # =========================================

    title = Paragraph(
        "<b>Soil Health Card</b>",
        styles["Title"]
    )

    elements.append(title)

    elements.append(Spacer(1, 20))

    # =========================================
    # Farmer Details
    # =========================================

    farmer_info = [
        ["Farmer Name", farmer.full_name],
        ["Mobile", farmer.mobile_number],
        ["Village", farmer.village],
        ["District", farmer.district],
        ["State", farmer.state],
        ["Sample Code", soil_test.sample_code]
    ]

    farmer_table = Table(
        farmer_info,
        colWidths=[150, 300]
    )

    farmer_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgreen),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica")
        ])
    )

    elements.append(farmer_table)

    elements.append(Spacer(1, 20))

    # =========================================
    # Soil Interpretation
    # =========================================

    interpretation = interpret_soil_test(
        soil_test
    )

    soil_data = [
        ["Parameter", "Value", "Status"]
    ]

    for key, value in interpretation.items():

        if isinstance(value, dict):

            if "value" in value:

                soil_data.append([
                    key.upper(),
                    str(value.get("value")),
                    value.get("status")
                ])

    soil_table = Table(
        soil_data,
        colWidths=[150, 150, 150]
    )

    soil_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.green),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),

            ("BACKGROUND", (0, 1), (-1, -1), colors.beige)
        ])
    )

    elements.append(soil_table)

    elements.append(Spacer(1, 20))

    # =========================================
    # Recommendations
    # =========================================

    recommendations_title = Paragraph(
        "<b>Recommendations</b>",
        styles["Heading2"]
    )

    elements.append(recommendations_title)

    recommendations = []

    for key, value in interpretation.items():

        if isinstance(value, dict):

            recommendation = value.get(
                "recommendation"
            )

            if recommendation:
                recommendations.append(
                    [key.upper(), recommendation]
                )

    recommendation_table = Table(
        recommendations,
        colWidths=[150, 300]
    )

    recommendation_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.orange),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("FONTNAME", (0, 0), (-1, -1), "Helvetica")
        ])
    )

    elements.append(recommendation_table)

    elements.append(Spacer(1, 20))

    # =========================================
    # Soil Health Score
    # =========================================

    soil_health = interpretation.get(
        "soil_health"
    )

    if soil_health:

        health_para = Paragraph(
            f"""
            <b>Soil Health Score:</b>
            {soil_health['score']}<br/>

            <b>Category:</b>
            {soil_health['category']}
            """,
            styles["BodyText"]
        )

        elements.append(health_para)

    elements.append(Spacer(1, 30))

    # =========================================
    # Footer
    # =========================================

    footer = Paragraph(
        "Generated by Agro Intelligence Platform",
        styles["Italic"]
    )

    elements.append(footer)

    # Build PDF
    doc.build(elements)

    return file_path
